# Generated by Django 3.2 on 2022-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empanelment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=500)),
                ('status', models.IntegerField(choices=[('contacted', 'contacted'), ('inprocess', 'inprocess'), ('verified', 'verified'), ('refused', 'refused')], default=2)),
            ],
        ),
    ]
