# Generated by Django 3.2 on 2022-07-09 16:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empanelment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=500)),
                ('project_topic', models.CharField(default='project topic', max_length=200)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('contacted', 'contacted'), ('inprocess', 'inprocess'), ('verified', 'verified'), ('refused', 'refused')], default='contacted', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MetaExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=500)),
                ('project_topic', models.CharField(default='project topic', max_length=200)),
                ('education', djongo.models.fields.JSONField(default=[])),
                ('experience', djongo.models.fields.JSONField(default=[])),
                ('price', models.IntegerField(blank=True, null=True)),
                ('geography', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
                ('profile_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
