# Generated by Django 3.2 on 2022-05-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empanelment',
            name='status',
            field=models.CharField(choices=[('contacted', 'contacted'), ('inprocess', 'inprocess'), ('verified', 'verified'), ('refused', 'refused')], default='contacted', max_length=20),
        ),
    ]
