# Generated by Django 3.2 on 2022-06-15 04:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_empanelment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=500)),
                ('project_topic', models.CharField(default='project topic', max_length=200)),
                ('biography', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('geography', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
                ('profile_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='empanelment',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='empanelment',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='empanelment',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empanelment',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empanelment',
            name='project_topic',
            field=models.CharField(default='project topic', max_length=200),
        ),
        migrations.AddField(
            model_name='empanelment',
            name='title',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='empanelment',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empanelment',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
