# Generated by Django 3.2 on 2022-06-01 11:24

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_empanelment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=500)),
                ('biography', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('geography', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', djongo.models.fields.JSONField(blank=True, default=[], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empanelment',
            name='project_topic',
            field=models.CharField(default='Project Topic', max_length=200),
        ),
        migrations.AlterField(
            model_name='empanelment',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empanelment',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
