# Generated by Django 3.2 on 2022-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_metaexpert_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaexpert',
            name='project_topic',
            field=models.CharField(default='Project Topic', max_length=200),
        ),
    ]
