# Generated by Django 3.2 on 2022-06-13 06:09

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_metaexpert_project_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empanelment',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='metaexpert',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='empanelment',
            name='comments',
            field=djongo.models.fields.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AddField(
            model_name='empanelment',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='empanelment',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='metaexpert',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='metaexpert',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='empanelment',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
