# Generated by Django 3.2 on 2022-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220613_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='empanelment',
            name='title',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='metaexpert',
            name='title',
            field=models.CharField(default='', max_length=5),
        ),
    ]
